// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nw.domain;

import com.nw.domain.RowOCS;

privileged aspect RowOCS_Roo_JavaBean {
    
    public Integer RowOCS.getRowIndexId() {
        return this.rowIndexId;
    }
    
    public void RowOCS.setRowIndexId(Integer rowIndexId) {
        this.rowIndexId = rowIndexId;
    }
    
}
