// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nw.domain;

import com.nw.domain.TriggerFieldFormat;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TriggerFieldFormat_Roo_Configurable {
    
    declare @type: TriggerFieldFormat: @Configurable;
    
}
